# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  order-api:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 8083
      MONGO_URI: mongodb://root:example@order-db:27017/order?authsource=admin
    ports:
      - 8084:8083
    networks:
      - order-network
    depends_on:
      - order-db
  order-db:
    image: mongo
    restart: always
    command: ["--bind_ip_all"]
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INIT_DATABASE: init-db
    volumes:
      - ./mongo-data:/data/db
    networks:
      - order-network
networks:
  order-network:
   driver: bridge


